import type { DemoScenario } from "./types"

// 13 demo-сценариев. Каждый сценарий — детерминированный скрипт диалога
// с переходами state machine, событиями и результатом.
// Реальные звонки и внешние API не используются.

export const DEMO_SCENARIOS: DemoScenario[] = [
  {
    id: "school-enroll",
    companyId: "school-astana",
    title: "Школа: запись на собеседование в 1 класс",
    context: "Мама интересуется местами в 1 класс и стоимостью, записывается на собеседование.",
    clientName: "Айгерим",
    clientPhone: "+7 701 234 56 78",
    expectedOutcome: "booking_created",
    createsLead: true,
    createsBooking: true,
    createsHandoff: null,
    followUps: [{ channel: "whatsapp", reason: "Подтверждение записи и адрес школы" }],
    steps: [
      { role: "system", text: "Входящий звонок на номер школы «Білім Плюс»", toState: "received", event: "voice.call.started" },
      { role: "assistant", text: "Здравствуйте! Это голосовой ассистент школы «Білім Плюс». Чем могу помочь?", toState: "greeting" },
      { role: "assistant", text: "Для качества обслуживания разговор обрабатывается ассистентом. Продолжаем?", toState: "consent" },
      { role: "client", text: "Да, конечно. Скажите, есть ли у вас места в первый класс на следующий год?", event: "voice.consent.received" },
      { role: "assistant", text: "Да, на 2026/27 учебный год есть 8 свободных мест в первый класс.", toState: "identifying_intent", event: "voice.intent.detected" },
      { role: "client", text: "Отлично! А сколько стоит обучение?" },
      { role: "assistant", text: "Обучение в 1–4 классах — 180 000 тенге в месяц, включая трёхразовое питание. Вступительный взнос — 150 000 тенге.", toState: "consulting" },
      { role: "client", text: "Понятно. А как проходит зачисление?" },
      { role: "assistant", text: "Сначала собеседование с ребёнком и родителями. Подскажите, ребёнку уже исполнилось 6 лет?", toState: "qualifying" },
      { role: "client", text: "Да, в марте исполнилось шесть." },
      { role: "assistant", text: "Отлично, подходим по возрасту. Как я могу к вам обращаться и по какому номеру с вами связаться?", toState: "lead_capture" },
      { role: "client", text: "Айгерим, номер +7 701 234 56 78." },
      { role: "system", text: "Лид создан и отправлен в CRM (mock)", event: "voice.lead.created" },
      { role: "assistant", text: "Спасибо, Айгерим! Могу записать вас на собеседование. Есть время в среду в 15:00 или в четверг в 10:00. Что удобнее?", toState: "booking" },
      { role: "client", text: "Среда, 15:00 подойдёт." },
      { role: "system", text: "Запись создана в календаре (mock)", event: "voice.booking.created" },
      { role: "assistant", text: "Записала вас на среду, 15:00. Отправлю подтверждение и адрес в WhatsApp. Ждём вас!", toState: "follow_up", event: "voice.followup.created" },
      { role: "client", text: "Спасибо большое, до свидания!" },
      { role: "assistant", text: "До свидания, Айгерим! Хорошего дня.", toState: "completed", event: "voice.call.completed" },
    ],
  },
  {
    id: "clinic-appointment",
    companyId: "clinic-almaty",
    title: "Клиника: запись к кардиологу",
    context: "Клиент хочет записаться к кардиологу, уточняет цену и подготовку.",
    clientName: "Марат",
    clientPhone: "+7 707 111 22 33",
    expectedOutcome: "booking_created",
    createsLead: true,
    createsBooking: true,
    createsHandoff: null,
    followUps: [{ channel: "sms", reason: "Подтверждение записи и напоминание" }],
    steps: [
      { role: "system", text: "Входящий звонок в клинику MedCity", toState: "received", event: "voice.call.started" },
      { role: "assistant", text: "Добрый день! Клиника MedCity, голосовой ассистент. Слушаю вас.", toState: "greeting" },
      { role: "assistant", text: "Разговор обрабатывается ассистентом для записи. Продолжаем?", toState: "consent" },
      { role: "client", text: "Да. Мне нужно к кардиологу записаться.", event: "voice.consent.received" },
      { role: "assistant", text: "Конечно, запишу вас к кардиологу. Приём стоит 12 000 тенге.", toState: "identifying_intent", event: "voice.intent.detected" },
      { role: "client", text: "А нужно что-то с собой брать?" },
      { role: "assistant", text: "Возьмите удостоверение личности и, если есть, прошлые кардиограммы. Это первый визит к нашему кардиологу?", toState: "consulting" },
      { role: "client", text: "Да, первый. Врач посоветовал проверить сердце." },
      { role: "assistant", text: "Поняла. Как к вам обращаться и оставьте, пожалуйста, номер телефона.", toState: "qualifying" },
      { role: "client", text: "Марат, +7 707 111 22 33.", toState: "lead_capture" },
      { role: "system", text: "Лид создан и отправлен в CRM (mock)", event: "voice.lead.created" },
      { role: "assistant", text: "Спасибо, Марат. Ближайшее время у кардиолога: завтра 11:30 или пятница 16:00. Что удобнее?", toState: "booking" },
      { role: "client", text: "Давайте завтра в 11:30." },
      { role: "system", text: "Запись создана в календаре (mock)", event: "voice.booking.created" },
      { role: "assistant", text: "Записала на завтра, 11:30, кардиолог. Пришлю SMS с подтверждением. Приходите за 10 минут.", toState: "follow_up", event: "voice.followup.created" },
      { role: "client", text: "Хорошо, спасибо." },
      { role: "assistant", text: "Будем ждать вас, Марат. Всего доброго!", toState: "completed", event: "voice.call.completed" },
    ],
  },
  {
    id: "beauty-booking",
    companyId: "beauty-astana",
    title: "Салон красоты: запись на окрашивание",
    context: "Клиентка записывается на окрашивание к конкретному мастеру.",
    clientName: "Дария",
    clientPhone: "+7 705 987 65 43",
    expectedOutcome: "booking_created",
    createsLead: true,
    createsBooking: true,
    createsHandoff: null,
    followUps: [{ channel: "whatsapp", reason: "Подтверждение записи" }],
    steps: [
      { role: "system", text: "Входящий звонок в салон Aura", toState: "received", event: "voice.call.started" },
      { role: "assistant", text: "Здравствуйте! Салон красоты Aura. Я голосовой ассистент, помогу записаться.", toState: "greeting" },
      { role: "assistant", text: "Разговор обрабатывается ассистентом. Продолжим?", toState: "consent" },
      { role: "client", text: "Да. Хочу записаться на окрашивание к Аружан.", event: "voice.consent.received" },
      { role: "assistant", text: "Отличный выбор! Окрашивание у Аружан — от 20 000 тенге, зависит от длины.", toState: "identifying_intent", event: "voice.intent.detected" },
      { role: "client", text: "У меня волосы до плеч, сложное окрашивание не нужно, просто в один тон." },
      { role: "assistant", text: "Поняла, окрашивание в один тон. Как вас зовут и ваш номер для записи?", toState: "qualifying" },
      { role: "client", text: "Дария, +7 705 987 65 43.", toState: "lead_capture" },
      { role: "system", text: "Лид создан (mock CRM)", event: "voice.lead.created" },
      { role: "assistant", text: "Спасибо, Дария! У Аружан свободно: суббота 12:00 или воскресенье 15:00.", toState: "booking" },
      { role: "client", text: "Суббота 12:00." },
      { role: "system", text: "Запись создана (mock календарь)", event: "voice.booking.created" },
      { role: "assistant", text: "Записала: суббота, 12:00, окрашивание у Аружан. Отправлю подтверждение в WhatsApp.", toState: "follow_up", event: "voice.followup.created" },
      { role: "client", text: "Спасибо!" },
      { role: "assistant", text: "Ждём вас в Aura, Дария! До субботы.", toState: "completed", event: "voice.call.completed" },
    ],
  },
  {
    id: "auto-diagnostic",
    companyId: "auto-almaty",
    title: "Автосервис: диагностика подвески",
    context: "Клиент жалуется на стук в подвеске, записывается на диагностику.",
    clientName: "Ержан",
    clientPhone: "+7 778 333 44 55",
    expectedOutcome: "booking_created",
    createsLead: true,
    createsBooking: true,
    createsHandoff: null,
    followUps: [{ channel: "sms", reason: "Подтверждение записи и адрес сервиса" }],
    steps: [
      { role: "system", text: "Входящий звонок в TopGear KZ", toState: "received", event: "voice.call.started" },
      { role: "assistant", text: "Здравствуйте! Автосервис TopGear. Голосовой ассистент на связи.", toState: "greeting" },
      { role: "assistant", text: "Разговор обрабатывается ассистентом. Продолжаем?", toState: "consent" },
      { role: "client", text: "Да. У меня Camry 70, стук спереди при езде по неровностям. Сколько будет стоить ремонт?", event: "voice.consent.received" },
      { role: "assistant", text: "Понимаю. Точную стоимость назовём только после диагностики — она стоит 10 000 тенге и бесплатна, если ремонтируетесь у нас.", toState: "identifying_intent", event: "voice.intent.detected" },
      { role: "client", text: "А долго диагностика занимает?" },
      { role: "assistant", text: "Диагностика ходовой занимает около 40 минут. Записать вас?", toState: "consulting" },
      { role: "client", text: "Да, давайте." },
      { role: "assistant", text: "Как к вам обращаться и оставьте номер телефона, пожалуйста.", toState: "qualifying" },
      { role: "client", text: "Ержан, +7 778 333 44 55.", toState: "lead_capture" },
      { role: "system", text: "Лид создан (mock CRM)", event: "voice.lead.created" },
      { role: "assistant", text: "Спасибо, Ержан. Есть время завтра в 10:00 или в 14:30. Когда удобнее?", toState: "booking" },
      { role: "client", text: "В 14:30." },
      { role: "system", text: "Запись создана (mock календарь)", event: "voice.booking.created" },
      { role: "assistant", text: "Записал: завтра 14:30, диагностика ходовой, Camry 70. SMS с адресом уже отправляю.", toState: "follow_up", event: "voice.followup.created" },
      { role: "client", text: "Отлично, до завтра." },
      { role: "assistant", text: "До завтра, Ержан! Хорошей дороги.", toState: "completed", event: "voice.call.completed" },
    ],
  },
  {
    id: "realty-buy",
    companyId: "realty-astana",
    title: "Недвижимость: подбор двухкомнатной квартиры",
    context: "Клиент ищет квартиру, ассистент квалифицирует и создаёт лид для брокера.",
    clientName: "Салтанат",
    clientPhone: "+7 702 456 78 90",
    expectedOutcome: "lead_created",
    createsLead: true,
    createsBooking: false,
    createsHandoff: null,
    followUps: [{ channel: "telegram", reason: "Подборка объектов от брокера" }],
    steps: [
      { role: "system", text: "Входящий звонок в Astana Estate", toState: "received", event: "voice.call.started" },
      { role: "assistant", text: "Добрый день! Astana Estate, голосовой ассистент. Подбираем недвижимость.", toState: "greeting" },
      { role: "assistant", text: "Разговор обрабатывается ассистентом. Продолжим?", toState: "consent" },
      { role: "client", text: "Да. Ищу двухкомнатную квартиру, покупка.", event: "voice.consent.received" },
      { role: "assistant", text: "Отлично, помогу. Какой район рассматриваете?", toState: "identifying_intent", event: "voice.intent.detected" },
      { role: "client", text: "Есиль, желательно ближе к набережной." },
      { role: "assistant", text: "Хороший район. Какой у вас бюджет?", toState: "qualifying" },
      { role: "client", text: "До 45 миллионов тенге, ипотека одобрена." },
      { role: "assistant", text: "Поняла: двухкомнатная, Есиль, до 45 млн, ипотека одобрена. Как вас зовут и куда прислать подборку?", toState: "lead_capture" },
      { role: "client", text: "Салтанат, +7 702 456 78 90, лучше в Telegram." },
      { role: "system", text: "Горячий лид создан (mock CRM), score 85", event: "voice.lead.created" },
      { role: "assistant", text: "Спасибо, Салтанат! Брокер подготовит подборку и отправит в Telegram сего��ня до вечера.", toState: "follow_up", event: "voice.followup.created" },
      { role: "client", text: "Буду ждать, спасибо." },
      { role: "assistant", text: "Хорошего дня, Салтанат! Скоро свяжемся.", toState: "completed", event: "voice.call.completed" },
    ],
  },
  {
    id: "resto-banquet",
    companyId: "resto-almaty",
    title: "Ресторан: бронь столика на юбилей",
    context: "Клиент бронирует столик на 6 человек на вечер пятницы.",
    clientName: "Гульнара",
    clientPhone: "+7 747 222 33 44",
    expectedOutcome: "booking_created",
    createsLead: true,
    createsBooking: true,
    createsHandoff: null,
    followUps: [{ channel: "sms", reason: "Подтверждение брони" }],
    steps: [
      { role: "system", text: "Входящий звонок в Dastarkhan", toState: "received", event: "voice.call.started" },
      { role: "assistant", text: "Добрый вечер! Ресторан Dastarkhan. Я помогу забронировать столик.", toState: "greeting" },
      { role: "assistant", text: "Разговор обрабатывается ассистентом. Продолжаем?", toState: "consent" },
      { role: "client", text: "Да. Хочу столик на пятницу, нас будет 6 человек, у мамы юбилей.", event: "voice.consent.received" },
      { role: "assistant", text: "Поздравляю с юбилеем! На пятницу есть столик у окна на 19:00 или VIP-кабинка на 20:00.", toState: "identifying_intent", event: "voice.intent.detected" },
      { role: "client", text: "А VIP-кабинка сколько стоит?" },
      { role: "assistant", text: "Кабинка без депозита, оплачиваете только заказ. Средний чек — около 12 000 тенге на гостя.", toState: "consulting" },
      { role: "client", text: "Тогда кабинку на 20:00." },
      { role: "assistant", text: "Отлично. На чьё имя бронь и ваш номер телефона?", toState: "lead_capture" },
      { role: "client", text: "Гульнара, +7 747 222 33 44." },
      { role: "system", text: "Контакт сохранён (mock CRM)", event: "voice.lead.created" },
      { role: "system", text: "Бронь создана (mock календарь)", event: "voice.booking.created", toState: "booking" },
      { role: "assistant", text: "Готово: пятница, 20:00, VIP-кабинка на 6 гостей. Отправлю SMS-подтверждение.", toState: "follow_up", event: "voice.followup.created" },
      { role: "client", text: "Спасибо большое!" },
      { role: "assistant", text: "Ждём вас в пятницу, Гульнара! Хорошего вечера.", toState: "completed", event: "voice.call.completed" },
    ],
  },
  {
    id: "shop-order-status",
    companyId: "shop-online",
    title: "Интернет-магазин: статус заказа и возврат",
    context: "Клиент уточняет статус заказа и оформляет возврат одной позиции.",
    clientName: "Тимур",
    clientPhone: "+7 708 999 88 77",
    expectedOutcome: "info_only",
    createsLead: false,
    createsBooking: false,
    createsHandoff: null,
    followUps: [{ channel: "email", reason: "Инструкция по возврату" }],
    steps: [
      { role: "system", text: "Входящий звонок в TezShop", toState: "received", event: "voice.call.started" },
      { role: "assistant", text: "Здравствуйте! TezShop, голосовой ассистент. Помогу с заказом или доставкой.", toState: "greeting" },
      { role: "assistant", text: "Разговор обрабатывается ассистентом. Продолжаем?", toState: "consent" },
      { role: "client", text: "Да. Где мой заказ 48213? Уже три дня жду.", event: "voice.consent.received" },
      { role: "assistant", text: "Проверяю заказ 48213... Он передан курьеру и будет доставлен завтра до 18:00.", toState: "identifying_intent", event: "voice.intent.detected" },
      { role: "client", text: "Хорошо. И ещё: я хочу вернуть наушники из прошлого заказа, не подошли." },
      { role: "assistant", text: "Конечно, возврат возможен в течение 14 дней. Оформляю заявку — курьер заберёт наушники при доставке завтрашнего заказа. Удобно?", toState: "consulting" },
      { role: "client", text: "Да, очень удобно." },
      { role: "system", text: "Заявка на возврат создана, инструкция отправлена на email (mock)", event: "voice.followup.created", toState: "follow_up" },
      { role: "assistant", text: "Готово. Отправил инструкцию по возврату на вашу почту. Что-то ещё?" },
      { role: "client", text: "Нет, спасибо." },
      { role: "assistant", text: "Хорошего дня, Тимур! Заказ будет завтра.", toState: "completed", event: "voice.call.completed" },
    ],
  },
  {
    id: "angry-customer",
    companyId: "shop-online",
    title: "Агрессивный клиент → передача менеджеру",
    context: "Клиент получил повреждённый товар, агрессивен. Ассистент сохраняет спокойствие и передаёт менеджеру.",
    clientName: "Виктор",
    clientPhone: "+7 777 000 11 22",
    expectedOutcome: "handoff",
    createsLead: true,
    createsBooking: false,
    createsHandoff: "aggression",
    followUps: [{ channel: "sms", reason: "Менеджер свяжется в течение 15 минут" }],
    steps: [
      { role: "system", text: "Входящий звонок в TezShop", toState: "received", event: "voice.call.started" },
      { role: "assistant", text: "Здравствуйте! TezShop, голосовой ассистент. Помогу с заказом или доставкой.", toState: "greeting" },
      { role: "assistant", text: "Разговор обрабатывается ассистентом. Продолжаем?", toState: "consent" },
      { role: "client", text: "Да что тут продолжать! Вы мне прислали разбитый монитор! Это вообще нормально?!", event: "voice.consent.received" },
      { role: "assistant", text: "Мне очень жаль, что так произошло. Это серьёзная ситуация, я помогу её решить.", toState: "identifying_intent", event: "voice.intent.detected" },
      { role: "client", text: "Верните деньги немедленно! Иначе я напишу жалобу в Роспотребнадзор!" },
      { role: "system", text: "Обнаружено критическое слово «возврат денег» + агрессия. Правило handoff сработало.", toState: "consulting" },
      { role: "assistant", text: "Понимаю ваше возмущение, Виктор. Претензии по повреждённому товару решает старший менеджер — я передаю ему ваш вопрос прямо сейчас с высоким приоритетом." },
      { role: "client", text: "Давайте быстрее!" },
      { role: "assistant", text: "Менеджер Алексей свяжется с вами в течение 15 минут по этому номеру. Я зафиксировала всю информацию о заказе и повреждении.", toState: "manager_handoff", event: "voice.handoff.requested" },
      { role: "system", text: "Handoff: причина — агрессия + претензия. Резюме передано менеджеру. SMS-подтверждение отправлено (mock).", event: "voice.followup.created" },
    ],
  },
  {
    id: "complex-question",
    companyId: "clinic-almaty",
    title: "Сложный вопрос вне базы знаний",
    context: "Клиент задаёт медицинский вопрос, на который ассистент не имеет права отвечать. Вопрос фиксируется, предлагается администратор.",
    clientName: null,
    clientPhone: "+7 701 555 66 77",
    expectedOutcome: "handoff",
    createsLead: false,
    createsBooking: false,
    createsHandoff: "out_of_knowledge",
    followUps: [],
    steps: [
      { role: "system", text: "Входящий звонок в клинику MedCity", toState: "received", event: "voice.call.started" },
      { role: "assistant", text: "Добрый день! Клиника MedCity, голосовой ассистент. Слушаю вас.", toState: "greeting" },
      { role: "assistant", text: "Разговор обрабатывается ассистентом для записи. Продолжаем?", toState: "consent" },
      { role: "client", text: "Да. Скажите, можно ли принимать варфарин вместе с антибиотиками? Мне назначили и то и другое.", event: "voice.consent.received" },
      { role: "assistant", text: "Это важный вопрос о совместимости лекарств — на него может ответить только врач, я не имею права давать медицинские рекомендации.", toState: "identifying_intent", event: "voice.intent.detected" },
      { role: "system", text: "Вопрос зафиксирован в списке «вопросы без ответа». Правило handoff: медицинский вопрос вне базы." },
      { role: "client", text: "А кто может подсказать? Это срочно." },
      { role: "assistant", text: "Я передам ваш вопрос администратору — он соединит вас с дежурным врачом. Если состояние ухудшается, звоните 103.", toState: "manager_handoff", event: "voice.handoff.requested" },
      { role: "system", text: "Handoff выполнен: причина — вопрос вне базы знаний. Вопрос сохранён для пополнения базы." },
    ],
  },
  {
    id: "ask-manager",
    companyId: "realty-astana",
    title: "Просьба соединить с менеджером",
    context: "Клиент сразу просит человека. Ассистент не удерживает, собирает минимум данных и передаёт.",
    clientName: "Бауыржан",
    clientPhone: "+7 700 123 45 67",
    expectedOutcome: "handoff",
    createsLead: true,
    createsBooking: false,
    createsHandoff: "customer_request",
    followUps: [],
    steps: [
      { role: "system", text: "Входящий звонок в Astana Estate", toState: "received", event: "voice.call.started" },
      { role: "assistant", text: "Добрый день! Astana Estate, голосовой ассистент. Подбираем недвижимость.", toState: "greeting" },
      { role: "assistant", text: "Разговор обрабатывается ассистентом. Продолжим?", toState: "consent" },
      { role: "client", text: "Да. Соедините меня, пожалуйста, сразу с живым менеджером.", event: "voice.consent.received" },
      { role: "assistant", text: "Конечно, соединю. Чтобы менеджер сразу был в курсе — подскажите в двух словах, по какому вопросу?", toState: "identifying_intent", event: "voice.intent.detected" },
      { role: "client", text: "Продаю коммерческое помещение 250 квадратов в центре, нужна оценка." },
      { role: "system", text: "Правило handoff: коммерческая недвижимость от 200 м² — старший брокер." },
      { role: "assistant", text: "Понял, это к старшему брокеру. Как к вам обращаться?", toState: "lead_capture" },
      { role: "client", text: "Бауыржан." },
      { role: "system", text: "Лид создан для брокера (mock CRM)", event: "voice.lead.created" },
      { role: "assistant", text: "Бауыржан, соединяю со старшим брокером Данияром. Он уже видит тему вашего звонка.", toState: "manager_handoff", event: "voice.handoff.requested" },
      { role: "system", text: "Handoff: причина — просьба клиента + правило компании (коммерческая недвижимость)." },
    ],
  },
  {
    id: "no-slots",
    companyId: "beauty-astana",
    title: "Нет свободного времени",
    context: "Все слоты у мастера заняты. Ассистент собирает желаемую дату и создаёт заявку в лист ожидания.",
    clientName: "Асель",
    clientPhone: "+7 706 444 55 66",
    expectedOutcome: "lead_created",
    createsLead: true,
    createsBooking: false,
    createsHandoff: null,
    followUps: [{ channel: "whatsapp", reason: "Уведомление при освобождении окна" }],
    steps: [
      { role: "system", text: "Входящий звонок в салон Aura", toState: "received", event: "voice.call.started" },
      { role: "assistant", text: "Здравствуйте! Салон красоты Aura. Я голосовой ассистент, помогу записаться.", toState: "greeting" },
      { role: "assistant", text: "Разговор обрабатывается ассистентом. Продолжим?", toState: "consent" },
      { role: "client", text: "Да. Запишите меня к Дане на маникюр на завтра.", event: "voice.consent.received" },
      { role: "assistant", text: "Проверяю расписание Даны на завтра... К сожалению, на завтра все окна у Даны заняты.", toState: "identifying_intent", event: "voice.intent.detected" },
      { role: "client", text: "Ох, а когда есть ближайшее?" },
      { role: "assistant", text: "Ближайшее окно у Даны — послезавтра в 13:00. Либо могу добавить вас в лист ожидания на завтра: если окно освободится, сразу напишем.", toState: "consulting" },
      { role: "client", text: "Давайте лист ожидания, и послезавтра пока не надо." },
      { role: "assistant", text: "Хорошо. Как вас зовут и номер для связи?", toState: "lead_capture" },
      { role: "client", text: "Асель, +7 706 444 55 66." },
      { role: "system", text: "Заявка в лист ожидания создана (mock CRM)", event: "voice.lead.created" },
      { role: "assistant", text: "Асель, добавила вас в лист ожидания на завтра к Дане. Если окно освободится — придёт сообщение в WhatsApp.", toState: "follow_up", event: "voice.followup.created" },
      { role: "client", text: "Спасибо!" },
      { role: "assistant", text: "Вам спасибо за звонок! Хорошего дня.", toState: "completed", event: "voice.call.completed" },
    ],
  },
  {
    id: "crm-failure",
    companyId: "auto-almaty",
    title: "Ошибка CRM: лид не теряется",
    context: "CRM недоступна в момент создания лида. Лид сохраняется локально, задача уходит в outbox/retry, клиент ничего не замечает.",
    clientName: "Нурлан",
    clientPhone: "+7 771 888 99 00",
    expectedOutcome: "booking_created",
    createsLead: true,
    createsBooking: true,
    createsHandoff: null,
    followUps: [{ channel: "sms", reason: "Подтверждение записи" }],
    steps: [
      { role: "system", text: "Входящий звонок в TopGear KZ", toState: "received", event: "voice.call.started" },
      { role: "assistant", text: "Здравствуйте! Автосервис TopGear. Голосовой ассистент на связи.", toState: "greeting" },
      { role: "assistant", text: "Разговор обрабатывается ассистентом. Продолжаем?", toState: "consent" },
      { role: "client", text: "Да. Нужна замена масла на Hyundai Tucson.", event: "voice.consent.received" },
      { role: "assistant", text: "Замена масла — от 5 000 тенге плюс материалы, займёт около 30 минут.", toState: "identifying_intent", event: "voice.intent.detected" },
      { role: "client", text: "Подходит. Запишите на субботу утром." },
      { role: "assistant", text: "Как к вам обращаться и ваш номер телефона?", toState: "lead_capture" },
      { role: "client", text: "Нурлан, +7 771 888 99 00." },
      { role: "system", text: "ОШИБКА: CRM недоступна (timeout). Лид сохранён локально, CRM job поставлен в outbox с retry. Клиент не уведомляется об ошибке.", error: "crm" },
      { role: "system", text: "Лид создан локально", event: "voice.lead.created" },
      { role: "assistant", text: "Спасибо, Нурлан. В субботу есть 09:00 и 11:00. Что удобнее?", toState: "booking" },
      { role: "client", text: "09:00." },
      { role: "system", text: "Запись создана (mock календарь)", event: "voice.booking.created" },
      { role: "assistant", text: "Записал: суббота, 09:00, замена масла, Tucson. Отправлю SMS-подтверждение.", toState: "follow_up", event: "voice.followup.created" },
      { role: "client", text: "Хорошо, спасибо." },
      { role: "system", text: "Retry #1: CRM снова доступна, лид синхронизирован, external ID получен.", event: "voice.usage.updated" },
      { role: "assistant", text: "До субботы, Нурлан!", toState: "completed", event: "voice.call.completed" },
    ],
  },
  {
    id: "calendar-failure",
    companyId: "clinic-almaty",
    title: "Ошибка календаря: заявка вместо записи",
    context: "Календарь недоступен. Ассистент собирает желаемую дату, создаёт заявку и честно сообщает, что менеджер подтвердит время.",
    clientName: "Жанна",
    clientPhone: "+7 705 222 11 00",
    expectedOutcome: "lead_created",
    createsLead: true,
    createsBooking: false,
    createsHandoff: null,
    followUps: [{ channel: "sms", reason: "Администратор подтвердит время в течение часа" }],
    steps: [
      { role: "system", text: "Входящий звонок в клинику MedCity", toState: "received", event: "voice.call.started" },
      { role: "assistant", text: "Добрый день! Клиника MedCity, голосовой ассистент. Слушаю вас.", toState: "greeting" },
      { role: "assistant", text: "Разговор обрабатывается ассистентом для записи. Продолжаем?", toState: "consent" },
      { role: "client", text: "Да, запишите меня на УЗИ брюшной полости.", event: "voice.consent.received" },
      { role: "assistant", text: "Конечно. УЗИ брюшной полости — от 7 000 тенге, натощак.", toState: "identifying_intent", event: "voice.intent.detected" },
      { role: "system", text: "ОШИБКА: календарь недоступен (connection refused). Переход к сценарию заявки. Booking job в outbox.", error: "calendar" },
      { role: "assistant", text: "Подскажите, на какой день и время вам удобно? Я оформлю заявку.", toState: "consulting" },
      { role: "client", text: "Лучше в четверг утром, до работы." },
      { role: "assistant", text: "Поняла: четверг, утро. Как вас зовут и оставьте номер телефона.", toState: "lead_capture" },
      { role: "client", text: "Жанна, +7 705 222 11 00." },
      { role: "system", text: "Заявка на запись создана локально (mock CRM)", event: "voice.lead.created" },
      { role: "assistant", text: "Жанна, заявка оформлена: УЗИ, четверг утром. Администратор подтвердит точное время в течение часа по SMS.", toState: "follow_up", event: "voice.followup.created" },
      { role: "client", text: "Хорошо, буду ждать." },
      { role: "assistant", text: "Спасибо за звонок! Напоминаю: УЗИ выполняется натощак. Всего доброго!", toState: "completed", event: "voice.call.completed" },
    ],
  },
  {
    id: "manager-unavailable",
    companyId: "resto-almaty",
    title: "Менеджер недоступен: заявка на обратный звонок",
    context:
      "Клиент просит менеджера, но все менеджеры заняты. Ассистент не теряет клиента: собирает контакты, создаёт лид и заявку на обратный звонок с follow-up.",
    clientName: "Алия",
    clientPhone: "+7 747 555 66 77",
    expectedOutcome: "lead_created",
    createsLead: true,
    createsBooking: false,
    createsHandoff: null,
    followUps: [{ channel: "whatsapp", reason: "Менеджер перезвонит в течение 30 минут" }],
    steps: [
      { role: "system", text: "Входящий звонок в Dastarkhan", toState: "received", event: "voice.call.started" },
      { role: "assistant", text: "Добрый день! Ресторан Dastarkhan. Я помогу забронировать столик.", toState: "greeting" },
      { role: "assistant", text: "Разговор обрабатывается ассистентом. Продолжаем?", toState: "consent" },
      { role: "client", text: "Да. Мне нужен менеджер банкетов, хочу обсудить свадьбу на 120 гостей.", event: "voice.consent.received" },
      { role: "assistant", text: "Конечно, банкеты ведёт наш менеджер. Проверяю, свободен ли он...", toState: "identifying_intent", event: "voice.intent.detected" },
      { role: "system", text: "ОШИБКА: попытка соединения — все менеджеры заняты (эмуляция). Soft-fail: переход к сценарию обратного звонка.", error: "provider" },
      { role: "assistant", text: "К сожалению, менеджер сейчас на другой линии. Чтобы вы не ждали — оставьте контакты, он перезвонит в течение 30 минут.", toState: "consulting" },
      { role: "client", text: "Хорошо, давайте так." },
      { role: "assistant", text: "Как к вам обращаться и по какому номеру перезвонить?", toState: "lead_capture" },
      { role: "client", text: "Алия, +7 747 555 66 77. Свадьба в сентябре, 120 гостей." },
      { role: "system", text: "Лид создан с высоким приоритетом: банкет 120 гостей (mock CRM)", event: "voice.lead.created" },
      { role: "assistant", text: "Записала, Алия: свадьба, сентябрь, 120 гостей. Менеджер банкетов перезвонит в течение 30 минут, подтверждение отправлю в WhatsApp.", toState: "follow_up", event: "voice.followup.created" },
      { role: "client", text: "Спасибо, жду звонка." },
      { role: "assistant", text: "Спасибо за звонок, Алия! Скоро свяжемся.", toState: "completed", event: "voice.call.completed" },
    ],
  },
]

export function getScenario(id: string): DemoScenario | undefined {
  return DEMO_SCENARIOS.find((s) => s.id === id)
}

export function getScenariosByCompany(companyId: string): DemoScenario[] {
  return DEMO_SCENARIOS.filter((s) => s.companyId === companyId)
}
